CREATE TABLE JOB_TITLE
(
    TITLE_ID NUMBER GENERATED AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NAME NVARCHAR2(50) NOT NULL,
    DESCRIPTION NVARCHAR2(200),
    CONSTRAINT PK_JOB_TITLE PRIMARY KEY
    (
        TITLE_ID
    )
);

CREATE SEQUENCE JOB_TITLE_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID NUMBER GENERATED AS IDENTITY (START WITH 10000 INCREMENT BY 1),
    FIRST_NAME NVARCHAR2(50) NOT NULL,
    LAST_NAME NVARCHAR2(50) NOT NULL,
    EMAIL NVARCHAR2(30)UNIQUE NOT NULL,
    ADDRESS NVARCHAR2(100) NOT NULL,
    HIRE_DATE DATE NOT NULL,
    END_DATE DATE NULL,
    DEPARTMENT_ID NUMBER NOT NULL,
    JOB_TITLE_ID NUMBER NOT NULL,
    CONSTRAINT PK_EMP_ID PRIMARY KEY
    (
        EMPLOYEE_ID
    ),
    CONSTRAINT CK_EMP_END_DATE
        CHECK(END_DATE >= HIRE_DATE),
    CONSTRAINT FK_EMP_JOBTITLE FOREIGN KEY
    (
        JOB_TITLE_ID
    )
    REFERENCES JOB_TITLE(TITLE_ID)
);

CREATE SEQUENCE EMP_SEQ
START WITH 10000
INCREMENT BY 1;

CREATE SEQUENCE DEP_SEQ
START WITH 100
INCREMENT BY 1;

CREATE SEQUENCE EMP_PHONE_SEQ
START WITH 1
INCREMENT BY 1;


CREATE TABLE DEPARTMENT
(
    DEPARTMENT_ID NUMBER GENERATED AS IDENTITY (START WITH 100 INCREMENT BY 1),
    NAME NVARCHAR2(50) UNIQUE NOT NULL,
    MANAGER_ID NUMBER UNIQUE,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY
    (
        DEPARTMENT_ID
    ),
    CONSTRAINT FK_EMPMANAGER_DEP FOREIGN KEY
    (
        MANAGER_ID
    )
    REFERENCES EMPLOYEE(EMPLOYEE_ID)
);


ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMP_DEP FOREIGN KEY
(
    DEPARTMENT_ID
)
REFERENCES DEPARTMENT(DEPARTMENT_ID);



CREATE TABLE EMPLOYEE_PHONE
(
    PHONE_ID NUMBER GENERATED AS IDENTITY (START WITH 1 INCREMENT BY 1),
    EMPLOYEE_ID NUMBER NOT NULL,
    PHONE_NUMBER NUMBER(10) NOT NULL,
    PHONE_TYPE NVARCHAR2(20) NOT NULL CHECK ( PHONE_TYPE IN ('Work','Mobile') ),
    CONSTRAINT PK_EMP_PHONE PRIMARY KEY
    (
        PHONE_ID
    ),
    CONSTRAINT FK_EMPPHONE_EMP FOREIGN KEY
    (
        EMPLOYEE_ID
    )
    REFERENCES EMPLOYEE(EMPLOYEE_ID)
);



CREATE SEQUENCE PROJ_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE PROJECT
(
    PROJECT_ID NUMBER GENERATED AS IDENTITY (START WITH 1 INCREMENT BY 1),
    TITLE NVARCHAR2(100) NOT NULL,
    DESCRIPTION NVARCHAR2(200),
    START_DATE DATE NOT NULL,
    END_DATE DATE NULL,
    STATUS NVARCHAR2(20) NOT NULL CHECK(STATUS IN ('ACTIVE', 'COMPLETED', 'ON_HOLD', 'CANCELLED')),
    CONSTRAINT PK_PROJ PRIMARY KEY
    (
        PROJECT_ID
    ),
    CONSTRAINT CK_PROJ_END_DATE
        CHECK(END_DATE >= START_DATE)
);


CREATE SEQUENCE EMP_PROJ_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE EMPLOYEE_PROJECT
(
    ID NUMBER GENERATED AS IDENTITY (START WITH 1 INCREMENT BY 1),
    EMPLOYEE_ID NUMBER NOT NULL,
    PROJECT_ID NUMBER NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NULL,
    STATUS NVARCHAR2(20) NOT NULL CHECK (STATUS IN ('ACTIVE', 'COMPLETED', 'ON_HOLD', 'CANCELLED')),
    CONSTRAINT PK_EMP_PROJ_ID PRIMARY KEY
    (
        ID
    ),
    CONSTRAINT CK_EMPPROJ_END_DATE
        CHECK (END_DATE >= START_DATE),
    CONSTRAINT FK_EMPPROJ_EMP FOREIGN KEY
    (
        EMPLOYEE_ID
    )
    REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT FK_EMPPROJ_PROJ FOREIGN KEY
    (
        PROJECT_ID
    )
    REFERENCES PROJECT(PROJECT_ID)
);



CREATE SEQUENCE PAY_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE PAYROLL
(
    PAYMENT_ID NUMBER GENERATED AS IDENTITY (START WITH 1 INCREMENT BY 1),
    EMPLOYEE_ID NUMBER NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    PAID_BASE_SALARY NUMBER(7,2) NOT NULL CHECK (PAID_BASE_SALARY >=  1880),
    BONUS_AMOUNT NUMBER(7,2) NULL CHECK (BONUS_AMOUNT >= 0),
    DEDUCTION_AMOUNT NUMBER(7,2) NULL CHECK (DEDUCTION_AMOUNT >= 0),
    NET_PAY NUMBER(7,2) GENERATED ALWAYS AS (PAID_BASE_SALARY + NVL(BONUS_AMOUNT,0) - NVL(DEDUCTION_AMOUNT,0)) VIRTUAL,
    CONSTRAINT PK_PAYROLL PRIMARY KEY
    (
        PAYMENT_ID
    ),
    CONSTRAINT FK_PAYROLL_EMP FOREIGN KEY
    (
        EMPLOYEE_ID
    )
    REFERENCES EMPLOYEE(EMPLOYEE_ID)
);



